"""

https://es.wikipedia.org/wiki/Prensa_de_Colombia



MEDIO_PRENSA (PK_NOMBRE_MEDIO, URL_MEDIO, AÑO_FUNDACION, COBERTURA, CONTINENTE, PAIS, REGION, CIUDAD, FK_ID_FUNDADOR)
FUNDADORES (PK_ID_FUNDADOR, NOMBRE_FUNDADOR, APELLIDO_FUNDADOR, FK_NOMBRE_MEDIO)
CATEGORIA (PK_ID_CATEGORIA, NOMBRE_CATEGORIA, FK_NOMBRE_MEDIO, URL_CATEGORIA)
RRSS (PK_ID_RRSS, USUARIO, ACTUALIZACION, SEGUIDORES, NOMBRE_RED, FK_NOMBRE_MEDIO)
NOTICIA (PK_ID_NOTICIA, XPATH_TITULO, XPATH_FECHA, XPATH_CONTENIDO, URL_NOTICIA, FK_NOMBRE_MEDIO)
FUNDADO_POR (FK_NOMBRE_MEDIO, FK_ID_FUNDADOR, FK_NOMBRE_FUNDADOR, FK_APELLIDO_FUNDADOR)
"""
import mysql.connector

# Conexión a la base de datos
connection = mysql.connector.connect(
        host='localhost',
        user='usuario', 
        password='contraseña')
cursor = connection.cursor()

# Creación de la base de datos
cursor.execute("CREATE DATABASE IF NOT EXISTS colombia")
cursor.execute("USE colombia")

# Creación de la tabla MEDIO_PRENSA
cursor.execute("""
    CREATE TABLE IF NOT EXISTS MEDIO_PRENSA (
        PK_NOMBRE_MEDIO VARCHAR(100) PRIMARY KEY,
        URL_MEDIO VARCHAR(100),
        AÑO_FUNDACION INT,
        COBERTURA VARCHAR(100),
        CONTINENTE VARCHAR(100),
        PAIS VARCHAR(100),
        REGION VARCHAR(100),
        CIUDAD VARCHAR(100),
        FK_URL_CATEGORIA VARCHAR(100),
        FK_NOMBRE_CATEGORIA VARCHAR(100),
        FOREIGN KEY (FK_URL_CATEGORIA, FK_NOMBRE_CATEGORIA) REFERENCES CATEGORIA(URL_CATEGORIA, PK_NOMBRE_CATEGORIA)
    )
""")

# Creación de la tabla FUNDADORES
cursor.execute("""
    CREATE TABLE IF NOT EXISTS FUNDADORES (
        PK_ID_FUNDADOR INT PRIMARY KEY,
        NOMBRE_FUNDADOR VARCHAR(100),
        APELLIDO_FUNDADOR VARCHAR(100)
    )
""")

# Creación de la tabla CATEGORIA
cursor.execute("""
    CREATE TABLE IF NOT EXISTS CATEGORIA (
        PK_NOMBRE_CATEGORIA VARCHAR(100) PRIMARY KEY,
        FK_NOMBRE_MEDIO VARCHAR(100),
        URL_CATEGORIA VARCHAR(100),
        FOREIGN KEY (FK_NOMBRE_MEDIO) REFERENCES MEDIO_PRENSA(PK_NOMBRE_MEDIO)
    )
""")

# Creación de la tabla RRSS
cursor.execute("""
    CREATE TABLE IF NOT EXISTS RRSS (
        PK_ID_RRSS INT PRIMARY KEY,
        USUARIO VARCHAR(100),
        ACTUALIZACION DATE,
        SEGUIDORES INT,
        NOMBRE_RED VARCHAR(100)
    )
""")

# Creación de la tabla FUNDADO_POR
cursor.execute("""
    CREATE TABLE IF NOT EXISTS FUNDADO_POR (
        FK_NOMBRE_MEDIO VARCHAR(100),
        FK_ID_FUNDADOR INT,
        FK_NOMBRE_FUNDADOR VARCHAR(100),
        FK_APELLIDO_FUNDADOR VARCHAR(100),
        FOREIGN KEY (FK_NOMBRE_MEDIO) REFERENCES MEDIO_PRENSA(PK_NOMBRE_MEDIO),
        FOREIGN KEY (FK_ID_FUNDADOR, FK_NOMBRE_FUNDADOR, FK_APELLIDO_FUNDADOR) REFERENCES FUNDADORES(PK_ID_FUNDADOR, NOMBRE_FUNDADOR, APELLIDO_FUNDADOR)
    )
""")

# Creación de la tabla TENER
cursor.execute("""
    CREATE TABLE IF NOT EXISTS TENER (
        FK_NOMBRE_MEDIO VARCHAR(100),
        FK_ID_RRSS INT,
        FOREIGN KEY (FK_NOMBRE_MEDIO) REFERENCES MEDIO_PRENSA(PK_NOMBRE_MEDIO),
        FOREIGN KEY (FK_ID_RRSS) REFERENCES RRSS(PK_ID_RRSS)
    )
""")

# Creación de la tabla NOTICIAS
cursor.execute("""
    CREATE TABLE IF NOT EXISTS NOTICIAS (
        PK_ID_NOTICIA INT PRIMARY KEY,
        FK_NOMBRE_MEDIO VARCHAR(100),
        TITULO VARCHAR(100),
        CONTENIDO VARCHAR(1000),
        FECHA DATE,
        FOREIGN KEY (FK_NOMBRE_MEDIO) REFERENCES MEDIO_PRENSA(PK_NOMBRE_MEDIO)
    )
""")

# Cierre de la conexión a la base de datos
connection.close()


#---------------------------------------------------------

